const XLSX = require('xlsx');

console.log('\n' + '='.repeat(80));
console.log('4. MỐI QUAN HỆ GIỮA CÁC CỘT');
console.log('='.repeat(80));
console.log('');
console.log('Mối quan hệ chính:');
console.log('  QCDate → Datetime: Khóa thời gian');
console.log('  MatID + Article → Material batch: Khóa bất biến');
console.log('  Model Name → Sản phẩm: Thông tin sản phẩm');
console.log('');
console.log('Tính toán tự động:');
console.log('  DefectedQty = Tổng lỗi từ các cột 400.01 - 400.12');
console.log('  % Defected = (DefectedQty / InspectionQty) × 100');
console.log('  ReleasedQty = InspectionQty - DefectedQty');
console.log('  PassQty = InspectionQty - DefectedQty');
console.log('  Received Rate = InspectionQty / ReceivedQty');
console.log('');
console.log('Phân tích Pareto:');
console.log('  Top defect: 400.11 (TACH LOP) - 16.1% dòng có dữ liệu');
console.log('  Defect ranking: M > L > O > N > P');
console.log('  80/20 analysis: Cần phân loại lỗi để tìm nguyên nhân chính');

console.log('\n' + '='.repeat(80));
console.log('5. CÁCH PIVOT/NHÓM DỮ LIỆU');
console.log('='.repeat(80));
console.log('');
console.log('Pivot 1: Chất lượng theo Ngày');
console.log('  Group By: QCDate');
console.log('  Sum: DefectedQty, InspectionQty');
console.log('  Calculate: % Defected, Trend');
console.log('  KQ: Xu hướng chất lượng theo thời gian');
console.log('');
console.log('Pivot 2: Chất lượng theo Model');
console.log('  Group By: Model Name');
console.log('  Sum: DefectedQty, InspectionQty');
console.log('  Calculate: Defect Rate per model');
console.log('  KQ: Model nào có tỷ lệ lỗi cao?');
console.log('');
console.log('Pivot 3: Chất lượng theo Loại Lỗi');
console.log('  Group By: Defect type (400.01 - 400.12)');
console.log('  Sum: Số lỗi mỗi loại');
console.log('  Percentage: % mỗi loại lỗi');
console.log('  KQ: Pareto chart - Lỗi nào phổ biến?');
console.log('');
console.log('Pivot 4: Chất lượng Ngày x Model');
console.log('  Group By: QCDate, Model Name');
console.log('  Sum: DefectedQty, InspectionQty');
console.log('  KQ: Bảng chéo - Xu hướng chi tiết');
console.log('');
console.log('Pivot 5: Kiểm tra vs Nhận');
console.log('  Group By: QCDate');
console.log('  Sum: ReceivedQty, InspectionQty, ReleasedQty');
console.log('  Calculate: Inspection Rate, Release Rate');
console.log('  KQ: Hiệu suất kiểm tra');

console.log('\n' + '='.repeat(80));
console.log('6. CẤU TRÚC JSON/OBJECT ĐƯỢC CẬP NHẬT TỐI ƯU');
console.log('='.repeat(80));
console.log('');
console.log('Cấu trúc 1: Flat JSON (Dễ xử lý, PivotTable)');
console.log('{');
console.log('  recordId: 1,');
console.log('  qcDate: \"2026-06-04\",');
console.log('  material: {');
console.log('    matId: \"DH30\",');
console.log('    name: \"OUTSOLE+MIDSOLE #1\",');
console.log('    ry: \"AH2605-508\",');
console.log('    article: \"KK2502\"');
console.log('  },');
console.log('  product: {');
console.log('    modelName: \"SAMBA JANE W\"');
console.log('  },');
console.log('  quantity: {');
console.log('    received: 39,');
console.log('    inspected: 8,');
console.log('    released: 8,');
console.log('    defected: 0,');
console.log('    passRate: 100');
console.log('  },');
console.log('  defects: {');
console.log('    \"400.01_NHIEM_BAN\": 2,');
console.log('    \"400.07_MAU_SAC\": 18,');
console.log('    \"400.09_KEM_CHAT_LUONG\": 1,');
console.log('    \"400.11_TACH_LOP_4mm\": 3,');
console.log('    \"400.12_TACH_LOP_4mm_down\": 1');
console.log('  },');
console.log('  metrics: {');
console.log('    defectRate: 0.0,');
console.log('    inspectionRate: 0.2051,');
console.log('    quality_score: 100');
console.log('  }');
console.log('}');

console.log('');
console.log('Cấu trúc 2: Normalized (Cho DB - SQL/NoSQL)');
console.log('{');
console.log('  inspection: {');
console.log('    _id: \"INS_0001\",');
console.log('    qcDate: ISODate(\"2026-06-04\"),');
console.log('    materialId: \"DH30\",');
console.log('    articleId: \"KK2502\",');
console.log('    modelId: \"SAMBA_JANE_W\",');
console.log('    quantities: { received: 39, inspected: 8, released: 8 }');
console.log('  },');
console.log('  defect_log: {');
console.log('    inspectionId: \"INS_0001\",');
console.log('    defectCode: \"400.11\",');
console.log('    defectName: \"TACH_LOP\",');
console.log('    count: 3,');
console.log('    severity: \"high\"');
console.log('  }');
console.log('}');

console.log('');
console.log('Cấu trúc 3: Time Series (Cho phân tích trend)');
console.log('{');
console.log('  date: \"2026-06-04\",');
console.log('  hourly_summary: [');
console.log('    { hour: 0, defect_rate: 0.0, inspections: 8, defects: 0 },');
console.log('    ...');
console.log('  ],');
console.log('  daily_stats: {');
console.log('    total_inspected: 15000,');
console.log('    total_defected: 500,');
console.log('    defect_rate: 3.33,');
console.log('    by_model: { \"SAMBA_JANE_W\": { rate: 2.5, count: 20 }, ... }');
console.log('  }');
console.log('}');

console.log('\n' + '='.repeat(80));
console.log('7. KHUYẾN NGHỊ MODULE NODE.JS PHÙ HỢP');
console.log('='.repeat(80));
console.log('');
console.log('✓ Đã cài đặt: xlsx (0.18.5)');
console.log('');
console.log('Khuyến nghị thêm:');
console.log('');
console.log('1. PIVOT TABLE: npm install pivot-table');
console.log('   - Ưu: Dễ dùng, cú pháp gần Excel');
console.log('   - Nhược: Performance thấp với dữ liệu lớn (380 rows ok)');
console.log('   - Dùng khi: Cần pivot nhanh, data nhỏ < 10K rows');
console.log('');
console.log('2. DATA-FORGE: npm install danfo-js');
console.log('   - Ưu: Powerful, như Pandas (Python), nhiều function phân tích');
console.log('   - Nhược: File size lớn');
console.log('   - Dùng khi: Phân tích dữ liệu phức tạp, thống kê');
console.log('');
console.log('3. DANFO.JS: npm install danfo-js');
console.log('   - Ưu: Giống Pandas, hỗ trợ lớn cho data science');
console.log('   - Nhược: Mới, community nhỏ');
console.log('   - Dùng khi: Học machine learning, phân tích stats');
console.log('');
console.log('4. MSSQL-NODEJS: npm install mssql');
console.log('   - Ưu: Lưu trữ, query SQL native');
console.log('   - Nhược: Cần SQL Server');
console.log('   - Dùng khi: Dữ liệu lớn, cần persistent storage');
console.log('');
console.log('5. LODASH: npm install lodash (đã phổ biến)');
console.log('   - Ưu: Grouping, sorting, filtering cơ bản');
console.log('   - Dùng khi: Xử lý dữ liệu đơn giản mà không cần library nặng');
console.log('');
console.log('KHUYẾN CÁO TỔNG HỢP:');
console.log('  - Bước 1: Dùng XLSX đọc file (đã có)');
console.log('  - Bước 2: Transform sang JSON cấu trúc 1 (Flat JSON)');
console.log('  - Bước 3: Nhóm dữ liệu với Lodash + custom groupBy');
console.log('  - Bước 4: Tính toán Pareto analysis (Defect ranking)');
console.log('  - Bước 5: Lưu kết quả Pivot trong DB hoặc JSON file');
console.log('  - Bước 6 (Optional): Dùng Danfo.js nếu cần phân tích stats');

console.log('\n' + '='.repeat(80));
